name: Terraform

on:
  push:
    branches:
      - main  # Change this to your default branch 

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.0.0

    - name: Build zip file
      run: |
        cd src
        zip -r ../function_code.zip .
        cd ..

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.6  # Specify your desired Terraform version

    - name: Authenticate to Google Cloud
      run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > "${HOME}/gcloud.json"

    - name: Set Google Cloud Credentials
      run: gcloud auth activate-service-account --key-file=${HOME}/gcloud.json
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      
    - name: Terraform Init
      run: terraform init

    - name : Terraform Plan
      run: terraform plan
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}


    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
